
[country]

country_name = COUNTRY
tool_title = 
currency = DOL

[drt_functionality]

Order Evaluation = TRUE
Dispatch Optimization = True
Release Notes = True

[dro_specs]

Include Return Leg Cost = True
Enforce Volume Capacity = True
Enforce Weight Capacity = True
Enforce Distance Limit = True
Enforce Transit Time Limit = True
Enforce Delivery Time Limit = True
Allow Missed Deliveries = True
Optimization Runtime Limit = True
Adjust Transit Time by Speed = True

[baseline]
predefined_routes = True