
[country]

country_name = Kenya
tool_title = 
currency = KES

[drt_functionality]

Order Evaluation = 
Dispatch Optimization = True
Release Notes = True

[dro_specs]

Include Return Leg Cost = True
Enforce Volume Capacity =
Enforce Weight Capacity =
Enforce Distance Limit = True
Enforce Transit Time Limit =
Enforce Delivery Time Limit =
Allow Missed Deliveries = True
Optimization Runtime Limit =  True
Adjust Transit Time by Speed =

[baseline]
predefined_routes = True